backend:
  name: azure
  repo: nhnfelles/Helsenorge/HN-Designsystem
  branch: master
  tenant_id: 412637ba-c32a-41ce-abb5-b60abad7c191
  app_id: 57031404-4c9f-4cc3-8418-ad4e9ef0190e
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: web/static/img
public_folder: /img

aliases:
  - &BODY {
      label: 'Innhold',
      name: 'body',
      widget: 'mdx',
      hint:
        'Følgende react-komponenter kan benyttes: ColorWall, Preamble, IconWall, LiveComponent. Eksempel på bruk: <ColorWall></ColorWall>',
    }

project: &ABOUT
  - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'about-page' }
  - { label: 'Tittel', name: 'title', widget: 'string' }
  - { label: 'Ingress', name: 'preamble', widget: 'mdx', required: false }
  - { label: 'Filer', name: 'pdf', widget: 'file', media_library: { config: { multiple: true } } }
  - <<: *BODY

project2: &PAGE
  - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'simple-page' }
  - { label: 'Tittel', name: 'title', widget: 'string' }
  - { label: 'Ingress', name: 'preamble', widget: 'mdx', required: false }
  - <<: *BODY

menu-item: &MENU
  - { label: Navn, name: label, widget: string }
  - { label: Path, name: path, widget: string }
  - label: Sub meny
    name: children
    widget: list
    fields:
      - { label: Navn, name: label, widget: string }
      - { label: Path, name: path, widget: string }

collections:
  - name: 'main-pages'
    label: 'Hovedsider'
    extension: mdx
    format: frontmatter
    files:
      - file: 'web/src/cms-pages/merkevare/index.mdx'
        label: 'Merkevare'
        name: 'merkevare'
        slug: '{{slug}}'
        fields: *PAGE
      - file: 'web/src/cms-pages/redaksjonelle-retningslinjer/index.mdx'
        label: 'Redaksjonelle Retningslinjer'
        name: 'redaksjonelle-retningslinjer'
        slug: '{{slug}}'
        fields: *PAGE
      - file: 'web/src/cms-pages/profilmateriell/index.mdx'
        label: 'Profilmateriell'
        name: 'profilmateriell'
        slug: '{{slug}}'
        fields: *PAGE
      - file: 'web/src/cms-pages/patterns/index.mdx'
        label: 'Mønstre'
        name: 'monstre'
        slug: '{{slug}}'
        fields: *PAGE

  - name: 'merkevare'
    label: 'Merkevare'
    extension: mdx
    format: frontmatter
    folder: 'web/src/cms-pages/merkevare'
    create: true
    slug: '{{slug}}'
    fields: *PAGE

  - name: 'redaksjonelle-retningslinjer'
    label: 'Redaksjonelle Retningslinjer'
    extension: mdx
    format: frontmatter
    folder: 'web/src/cms-pages/redaksjonelle-retningslinjer'
    create: true
    slug: '{{slug}}'
    fields: *PAGE

  - name: 'profilmateriell'
    label: 'Profilmateriell'
    extension: mdx
    format: frontmatter
    folder: 'web/src/cms-pages/profilmateriell'
    create: true
    slug: '{{slug}}'
    fields: *PAGE

  - name: 'monstre'
    label: 'Mønstre'
    extension: mdx
    format: frontmatter
    folder: 'web/src/cms-pages/monstre'
    create: true
    slug: '{{slug}}'
    fields: *PAGE

  - name: 'other-pages'
    label: 'Andre sider'
    extension: mdx
    format: frontmatter
    files:
      - file: 'web/src/cms-pages/about.mdx'
        label: 'About'
        name: 'about'
        slug: '{{slug}}'
        fields: *ABOUT
      - file: 'web/src/cms-pages/contribute.mdx'
        label: 'Contribute'
        name: 'contribute'
        slug: '{{slug}}'
        fields: *PAGE
      - file: 'web/src/cms-pages/principles.mdx'
        label: 'Principles'
        name: 'principles'
        slug: '{{slug}}'
        fields: *PAGE
      - file: 'web/src/cms-pages/privacy.mdx'
        label: 'Privacy'
        name: 'privacy'
        slug: '{{slug}}'
        fields: *PAGE
      - file: 'web/src/cms-pages/roadmap.mdx'
        label: 'Roadmap'
        name: 'roadmap'
        slug: '{{slug}}'
        fields: *PAGE
      - file: 'web/src/cms-pages/terms-of-use.mdx'
        label: 'Terms of use'
        name: 'terms-of-use'
        slug: '{{slug}}'
        fields: *PAGE

  - name: settings
    label: Innstillinger
    files:
      - file: web/src/settings/routes.json
        label: Meny
        name: routes
        fields:
          - label: Bibliotek
            name: bibliotek
            widget: list
            fields: *MENU
          - label: Merkevare
            name: merkevare
            widget: list
            fields: *MENU
          - label: Mønster
            name: monster
            widget: list
            fields: *MENU
          - label: Redaksjonelle Retningslinjer
            name: redaksjonelle-retningslinjer
            widget: list
            fields: *MENU
          - label: Profilmateriell
            name: profilmateriell
            widget: list
            fields: *MENU
